### ISSUE TITLE
Performing actions on keypress

### ISSUE THREAD

**Issue by freekmurze** [clue/php-stdio-react#49]
First of all, thank you for your excellent work on this. Really like the package.

I'm having trouble figuring out how actions could be performed on keypress. 

This is the screen of a console app I'm building
![screen shot 2017-08-01 at 23 12 20](https://user-images.githubusercontent.com/483853/28849280-ab6eba32-7716-11e7-819d-f29f9f575549.jpg)

This is [the code](https://github.com/spatie/phpunit-watcher/blob/3535eb0/src/Screens/PhpunitScreen.php#L26-L45) that tries to figure out which key has been pressed.

Unfortunately it know only works by pressing the letter and then `enter`. I want to get rid of the required press on `enter` to invoke the action.

How can this be achieved?

**Comment by freekmurze** [comment]
Tried a whole lot of variations to get this to work but no luck.

Latest attempt:

```php
        $this->io->getInput()->on($eventName, function ($line) use ($callable) {
            $callable($line);

            $this->io->getReadline()->setInput('')->clear();
        });
```

Hope to find a solution soon, this is the last problem I need to solve before tagging a new release of my package.

**Comment by thecrypticace** [comment]
I was peeking around (because of your tweet) and came up w/ pretty much the same solution as you. But that one works for me. Does it do something it shouldn't?

**Comment by freekmurze** [comment]
The thing is with that code in my previous comment, actions get executed multiple times. So pressing "a" runs the tests, pressing "a" again runs the tests twice, and so on. Can't find a good way to reset what has been typed before.

**Comment by thecrypticace** [comment]
Yeah, I noticed this but I can't figure out why. If I replace the callable with a simple echo I don't get repeated echoes or characters. Which is strange.

**Comment by thecrypticace** [comment]
Got it: `$this->io->getInput()->removeAllListeners();`

**Comment by thecrypticace** [comment]
That appears to work for at least the "all tests" case.

**Comment by freekmurze** [comment]
Mmm, I don't understand 100% how you fixed this.

Tried:

```php
        $this->io->getInput()->on($eventName, function ($line) use ($callable) {
            $callable(trim($line));

            $this->io->getInput()->removeAllListeners();
        });
```

Doesn't seem to be working...

**Comment by thecrypticace** [comment]
Oh sorry, in your Terminal.php's removeAllListeners method:
```php
public function removeAllListeners()
{
    $this->io->removeAllListeners();
    $this->io->getInput()->removeAllListeners(); // Added this line

    return $this;
}
```

This appears to break input on the filter screens though. Looking into that now.

**Comment by freekmurze** [comment]
Yeah, just figured it out and bumped on the breaking filter screens. Thanks for figuring this out together with me :-)

**Comment by thecrypticace** [comment]
👍

**Comment by freekmurze** [comment]
Got it!

https://github.com/spatie/phpunit-watcher/blob/feature-interactivity/src/Terminal.php#L25-L38

I'm thinking `removeAllListeners` removed some internal listeners as well. Solved it by using `once`.

**Comment by clue** [comment]
I'm glad you've got this sorted out already! Let's recap some of the nifty details here.

The following code will invoke the callback whenever data arrives on `STDIN`:

```php
$stdio->getInput()->on('data', function ($data) {
    var_dump($data);
});
```

If you only want to execute this callback *once* for when the *next* input arrives, you should indeed use `once()` instead:

```php
$stdio->getInput()->once('data', function ($data) {
    var_dump($data);
});
```
Both should work for the use case you've mentioned above, but note they actually work on raw data received from `STDIN`, which may expose more "data" than you may be aware of. This event will be emitted whenever new data on the `STDIN` stream is ready, which may not only include "user key presses".

In particular, special keys such as cursors or Fn will actually emit binary terminal codes that consist of multiple bytes (which may in turn contain ASCII bytes). Similarly, pressing non-ASCII keys such as `ä` will emit a single event with multiple bytes. Additionally, copy-pasting things into the terminal will emit a single event with multiple bytes.

To make things worse, keep in mind that the loop will process data as soon as it (is aware that it) arrives. This means that if you either block the loop or copy-paste big inputs, you may actually receive data in chunks which may contain multiple bytes. Additionally, these chunks can potentially be split at byte ranges so that a single UTF-8 characters can be broken into multiple chunks with incomplete UTF-8 sequences.

All of these are probably not an issue for your particular use case, so you should be able to consume this stream just fine. But these combined are the reason why the `Readline` class does all the heavy lifting internally and only exposes the `data` when the user presses ENTER.

I'm not opposed to exposing things through an easier API, but I'd love to hear some more thoughts on this first! Thanks for sparking this discussion, which I think is a very good step towards this API! :+1:

**Comment by freekmurze** [comment]
I'm not a big user of ReactPHP so I don't know what a good API for most users might be, this is just my two little cents with only my specific problem in mind.

For my package it would have been nice that a `$stdio->onKeypress($callable)` function would have been present.

**Comment by clue** [comment]
Thanks for all your input so far!

Note that the above code will have to be deprecated via #62 for the upcoming v1.2.0 release. This is required in preparation for the upcoming v2.0.0 release (#50).

A proper way to register custom functions to key events has been worked out already and will be added again with the v2.1.0 release that will be released shortly thereafter.

This means that you can keep relying on the above behavior with the old version for now and I will update this ticket again for the v2.1.0 release :+1:

**Comment by clue** [comment]
I've just filed #70 to add this for the upcoming release :shipit: 

I would love some feedback, so it would be much appreciated if anybody happens to have a chance to check this out before merging.
